VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DirParams"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public sinU1 As Double
Public cosU1 As Double
Public sigma As Double
Public sinSigma As Double
Public cosSigma As Double
Public cosAlpha1 As Double
Public cosSqAlpha As Double
Public cos2sigmaM As Double
Public sinAlpha As Double
Public sinAlpha1 As Double
Public lambda1 As Double

