VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "InvParams"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public upper_A As Double
Public sigma As Double
Public deltaSigma As Double
Public sinU1 As Double
Public cosU1 As Double
Public sinU2 As Double
Public cosU2 As Double
Public cosLambda As Double
Public sinLambda As Double

